server:
  port: 8080
spring:
  application:
    name: commercify-monolith
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/commercify-mono

